### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by jwcen** [qklee-lz/CDTM#2]
Dear author,
I'm very interested in your CDTM work and would like to know if your code has been published. I'm looking for a solution to a specific problem and think your project might be able to meet my needs. Have you already released the code or plan to release it in the future? If so, I'd be very grateful if you could provide me with a way to get the code.
Thank you for your attention and patient reply.

**Comment by qklee-lz** [comment]
I appreciate your interest in our work. Our paper has not yet been published, but a preprint has been submitted. Therefore, I think I can open source the code now. I will upload it here around the 20th of this month. Thanks♪(･ω･)ﾉ!

**Comment by jwcen** [comment]
> I appreciate your interest in our work. Our paper has not yet been published, but a preprint has been submitted. Therefore, I think I can open source the code now. I will upload it here around the 20th of this month. Thanks♪(･ω･)ﾉ!

That's great news! Thank you for considering open sourcing the code for your work. We really appreciate your efforts.

**Comment by qklee-lz** [comment]
> > I appreciate your interest in our work. Our paper has not yet been published, but a preprint has been submitted. Therefore, I think I can open source the code now. I will upload it here around the 20th of this month. Thanks♪(･ω･)ﾉ!
> 
> That's great news! Thank you for considering open sourcing the code for your work. We really appreciate your efforts.

I'm sorry, there are too many things going on at the end of the year, so I delayed 10 days. All the code has been uploaded now! If you only want to know the core part (CDTM module), just check ./CODE/models/modules.py.
